In [1]:
# Given probabilities
P_D = 0.01         # Probability of having the disease
P_Pos_D = 0.99     # Probability of testing positive given the disease (sensitivity)
P_Neg_Dc = 0.98    # Probability of testing negative given no disease (specificity)
P_Pos_Dc = 1 - P_Neg_Dc  # Probability of testing positive given no disease

# Total probability of testing positive
P_Pos = P_Pos_D * P_D + P_Pos_Dc * (1 - P_D)

# Applying Bayes' Theorem
P_D_Pos = (P_Pos_D * P_D) / P_Pos
print(f"Probability of having the disease given a positive test result: {P_D_Pos:.4f}")


Probability of having the disease given a positive test result: 0.3333


In [2]:
import numpy as np

# Given matrix
A = np.array([[4, 1], [2, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [3]:
import numpy as np

# Given matrix
B = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

# Calculate determinant
det_B = np.linalg.det(B)
print("Determinant of B:", det_B)

# Calculate inverse if determinant is non-zero
if det_B != 0:
    inv_B = np.linalg.inv(B)
    print("Inverse of B:\n", inv_B)
else:
    print("Matrix B is singular and does not have an inverse.")


Determinant of B: 0.9999999999999987
Inverse of B:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [4]:
import scipy.stats as stats

# Parameters for the normal distribution
mu = 0     # mean
sigma = 1  # standard deviation

# Calculate probability P(X <= x) for x = 1.96
x = 1.96
prob = stats.norm.cdf(x, mu, sigma)
print(f"Probability P(X <= {x}) for N({mu}, {sigma}^2): {prob:.4f}")

# Calculate the probability P(a <= X <= b)
a = -1.96
b = 1.96
prob_ab = stats.norm.cdf(b, mu, sigma) - stats.norm.cdf(a, mu, sigma)
print(f"Probability P({a} <= X <= {b}) for N({mu}, {sigma}^2): {prob_ab:.4f}")


Probability P(X <= 1.96) for N(0, 1^2): 0.9750
Probability P(-1.96 <= X <= 1.96) for N(0, 1^2): 0.9500
